import { Theme } from '@radix-ui/themes';
import './global.css';
import '@radix-ui/themes/styles.css';

export const metadata = {
  title: 'Welcome to y-gaming',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
