import './global.css';
import '@radix-ui/themes/styles.css';
import Providers from './provider';
import { Suspense } from 'react';
import LoadingPage from './loading';

export const metadata = {
  title: 'Z-Gaming',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<LoadingPage />}>
          <Providers>{children}</Providers>
        </Suspense>
      </body>
    </html>
  );
}
