import { applicationListSchema, AppsData } from './types';

export const generateAppData = (): AppsData[] => {
  const data: AppsData[] = [
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
    {
      id: '1',
      title: 'App One',
      category: { name: 'Education' },
      createdAt: '2023-01-01T00:00:00.000Z',
      download: '100',
      rating: 4.5,
      status: 'active',
    },
    {
      id: '2',
      title: 'App Two',
      category: { name: 'Productivity' },
      createdAt: '2023-02-01T00:00:00.000Z',
      download: '200',
      rating: 4.0,
      status: 'inactive',
    },
    {
      id: '3',
      title: 'App Three',
      category: { name: 'Entertainment' },
      createdAt: '2023-03-01T00:00:00.000Z',
      download: '300',
      rating: 3.5,
      status: 'active',
    },
    {
      id: '4',
      title: 'App Four',
      category: { name: 'Health' },
      createdAt: '2023-04-01T00:00:00.000Z',
      download: '400',
      rating: 5.0,
      status: 'inactive',
    },
    {
      id: '5',
      title: 'App Five',
      category: { name: 'Finance' },
      createdAt: '2023-05-01T00:00:00.000Z',
      download: '500',
      rating: 4.8,
      status: 'active',
    },
  ];

  // Validate and filter the data using applicationListSchema
  return data.filter(
    (mockCourse) => applicationListSchema.safeParse(mockCourse).success
  );
};


export const styles = [
  { name: 'input', style: 'bg-input' },
  { name: 'ring', style: 'bg-ring' },
  { name: 'background', style: 'bg-background' },
  { name: 'foreground', style: 'bg-foreground' },
  { name: 'destructive-DEFAULT', style: 'bg-destructive-DEFAULT' },
  { name: 'destructive-foreground', style: 'bg-destructive-foreground' },
  { name: 'muted-DEFAULT', style: 'bg-muted-DEFAULT' },
  { name: 'muted-foreground', style: 'bg-muted-foreground' },
  { name: 'popover-DEFAULT', style: 'bg-popover-DEFAULT' },
  { name: 'popover-foreground', style: 'bg-popover-foreground' },
  { name: 'card-DEFAULT', style: 'bg-card-DEFAULT' },
  { name: 'card-foreground', style: 'bg-card-foreground' },
  { name: 'primary', style: 'bg-primary' },
  { name: 'text-primary', style: 'bg-text-primary' },
  { name: 'text-secondary', style: 'bg-text-secondary' },
  { name: 'text-invert', style: 'bg-text-invert' },
  { name: 'text-brand', style: 'bg-text-brand' },
  { name: 'text-accent', style: 'bg-text-accent' },
  { name: 'text-success', style: 'bg-text-success' },
  { name: 'text-error', style: 'bg-text-error' },
  { name: 'text-link', style: 'bg-text-link' },
  { name: 'icon-primary', style: 'bg-icon-primary' },
  { name: 'icon-secondary', style: 'bg-icon-secondary' },
  { name: 'icon-invert', style: 'bg-icon-invert' },
  { name: 'icon-brand', style: 'bg-icon-brand' },
  { name: 'icon-accent', style: 'bg-icon-accent' },
  { name: 'icon-success', style: 'bg-icon-success' },
  { name: 'icon-error', style: 'bg-icon-error' },
  { name: 'icon-link', style: 'bg-icon-link' },
  { name: 'surface-primary', style: 'bg-surface-primary' },
  { name: 'surface-secondary', style: 'bg-surface-secondary' },
  { name: 'surface-invert', style: 'bg-surface-invert' },
  { name: 'surface-brand', style: 'bg-surface-brand' },
  { name: 'surface-brandLight', style: 'bg-surface-brandLight' },
  { name: 'surface-accent', style: 'bg-surface-accent' },
  { name: 'surface-accentLight', style: 'bg-surface-accentLight' },
  { name: 'surface-success', style: 'bg-surface-success' },
  { name: 'surface-error', style: 'bg-surface-error' },
  { name: 'surface-link', style: 'bg-surface-link' },
  { name: 'border-primary', style: 'bg-border-primary' },
  { name: 'border-secondary', style: 'bg-border-secondary' },
  { name: 'border-invert', style: 'bg-border-invert' },
  { name: 'border-brand', style: 'bg-border-brand' },
  { name: 'border-accent', style: 'bg-border-accent' },
  { name: 'border-success', style: 'bg-border-success' },
  { name: 'border-error', style: 'bg-border-error' },
  { name: 'border-link', style: 'bg-border-link' },
];
