export enum BOT_MANAGEMENT_TYPE {
  WELCOME = 'WELCOME',
  BEFORE_LOGIN = 'BEFORE_LOGIN',
  AFTER_LOGIN = 'AFTER_LOGIN',
  DOWNLOAD = 'DOWNLOAD',
  APP_LINK = 'APP_LINK',
}
export enum DOWNLOAD_TYPE {
  NONE = 'NONE',
  APP_STORE = 'APP_STORE',
  PLAY_STORE = 'PLAY_STORE',
  DIRECT_DOWNLOAD = 'DIRECT_DOWNLOAD',
}

export enum GUIDE_TYPE {
  DOWNLOAD = 'DOWNLOAD',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
}

export enum LEGAL_TYPE {
  DEPOSIT = 'DEPOSIT',
  DEPOSIT_BONUS = 'DEPOSIT_BONUS',
  DEPOSIT_TO_CONFIRM = 'DEPOSIT_TO_CONFIRM',
  DEPOSIT_CRYPTO_TO_CONFIRM = 'DEPOSIT_CRYPTO_TO_CONFIRM',
  WITHDRAW = 'WITHDRAW',
  POLICY = 'POLICY',
  TERMS = 'TERMS',
  POCKET_MONEY = 'POCKET_MONEY',
}

export enum ROLE_TYPE {
  SUPER_ADMIN = 'SUPER_ADMIN',
  WITHDRAW_ADMIN = 'WITHDRAW_ADMIN',
  DEPOSIT_ADMIN = 'DEPOSIT_ADMIN',
  SERVICE_ADMIN = 'SERVICE_ADMIN',
  CUSTOM_ADMIN = 'CUSTOM_ADMIN',
}
