import { GameTrackingType } from '../../../../types/gametrancking.types';

export const dummyGameList: GameTrackingType[] = [
  {
    mainGameName: 'Funny Game',
    operatorName: 'ZGB',
    url: 'https://www.google.com',
    userName: 'zgb',
    password: 'password',
    merchatCode: 'Customer Domain Name',
    vpnRequirement: true,
  },
  {
    mainGameName: 'Funny Game',
    operatorName: 'ZGB',
    url: 'https://www.google.com',
    userName: 'zgb',
    password: 'password',
    merchatCode: 'Customer Domain Name',
    vpnRequirement: true,
  },
  {
    mainGameName: 'Funny Game',
    operatorName: 'ZGB',
    url: 'https://www.google.com',
    userName: 'zgb',
    password: 'password',
    merchatCode: 'Customer Domain Name',
    vpnRequirement: true,
  },
  {
    mainGameName: 'Funny Game',
    operatorName: 'ZGB',
    url: 'https://www.google.com',
    userName: 'zgb',
    password: 'password',
    merchatCode: 'Customer Domain Name',
    vpnRequirement: true,
  },
  {
    mainGameName: 'Funny Game',
    operatorName: 'ZGB',
    url: 'https://www.google.com',
    userName: 'zgb',
    password: 'password',
    merchatCode: 'Customer Domain Name',
    vpnRequirement: true,
  },
  {
    mainGameName: 'Funny Game',
    operatorName: 'ZGB',
    url: 'https://www.google.com',
    userName: 'zgb',
    password: 'password',
    merchatCode: 'Customer Domain Name',
    vpnRequirement: true,
  },
  {
    mainGameName: 'Funny Game',
    operatorName: 'ZGB',
    url: 'https://www.google.com',
    userName: 'zgb',
    password: 'password',
    merchatCode: 'Customer Domain Name',
    vpnRequirement: true,
  },
  {
    mainGameName: 'Funny Game',
    operatorName: 'ZGB',
    url: 'https://www.google.com',
    userName: 'zgb',
    password: 'password',
    merchatCode: 'Customer Domain Name',
    vpnRequirement: true,
  },
];
